# Generated by Django 3.1.7 on 2021-03-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenbudgetapp', '0002_goalset_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalset',
            name='ym',
            field=models.CharField(default='yearly', max_length=100),
            preserve_default=False,
        ),
    ]
